### ISSUE TITLE
word-under-cursor tag lookups fail for Ruby methods ending in ! or ?

### ISSUE THREAD

**Issue by ivanbrennan** [ivanbrennan/dotvim#4]
Ruby allows for method names ending in a `!` or `?` character. When I'm in a Ruby project that's been indexed with ctags, I can use the `:tag` command to search for such a method, e.g.
```
:tag mymethod!
```
and Vim jumps to its definition. But if I try such a lookup via the normal-mode **`<C-]>`** key (search tags for the word under cursor), Vim omits the `!` from its search. The same is true for methods ending in `?`.

How can I fix this?

**Comment by ivanbrennan** [comment]
The problem stems from the fact that `!` and `?` are not keyword characters, so Vim treats them as punctuation and excludes them from the "word under cursor". You _could_ change this by doing,
```vim
" this is a bad idea
set iskeyword+=!
set iskeyword+=?
```
but I don't suggest it, as it causes other problems (e.g. `!some_predicate` gets treated as a method name containing a leading `!`).

Instead, a better workaround is to put the following in `~/.vim/ftplugin/ruby.vim`:
```vim
nnoremap <buffer><silent>  <C-]> :<C-U>exe v:count1."tag <Plug><cword>"<CR>
nnoremap <buffer><silent>     g] :<C-U>tselect <Plug><cword><CR>
nnoremap <buffer><silent> g<C-]> :<C-U>tjump   <Plug><cword><CR>
```
This makes use of a `<Plug><cword>` mapping provided by vim-ruby (and included in Vim's runtime files by default) provides to correctly identify the Ruby cursor identifier.

See:
https://github.com/vim-ruby/vim-ruby/commit/deb3490a0ecca3d2163863bb49e5a3adff875387
https://github.com/vim-ruby/vim-ruby/commit/2322c368736156413b7fac9f13521ed0e851fe70
https://github.com/vim-ruby/vim-ruby/commit/37ab22005b44605c1c5385d6551644c49199b691
https://github.com/vim-ruby/vim-ruby/blob/master/ftplugin/ruby.vim
https://github.com/vim/vim/blob/master/runtime/ftplugin/ruby.vim

**Comment by zachahn** [comment]
Hey Ivan! This is super cool!

I followed your directions above, but when trying to use ctags, I got an error `E426: tag not found: <Plug><cword>`.

I did manage to get it working after a while by installing `ivanbrennan/articulate` and using the snippet I found in your `ftplugin/ruby.vim`.

Just curious, do you know off hand why I was getting the error or why `articulate` fixed it? I'm happy that I got this working though, thanks for this info!

**Comment by ivanbrennan** [comment]
Hey @zachahn! I didn't realize it when I first wrote this, but tpope already wrote some excellent runtime files to handle Ruby identifiers correctly:

https://github.com/vim/vim/blob/master/runtime/ftplugin/ruby.vim#L211-L219
https://github.com/vim/vim/blob/master/runtime/ftplugin/ruby.vim#L157
https://github.com/vim/vim/blob/master/runtime/ftplugin/ruby.vim#L338-L350

The only reason I'm still rolling my own here is because I prefer `<C-.>` and `<C-,>` over `<C-]>` and `<C-t>` for navigating the tag stack. If you don't mind the default keybindings, this solution is probably not necessary (as long as you're running a relatively recent Vim).

In my case, I wanted to [use different keys](https://github.com/ivanbrennan/dotvim/blob/master/init/keybindings.vim#L223-L228), since `<C-]>` is so heavy on the pinkies (and I like the symmetry of using `.` and `,`):
```viml
nmap  <C-.>  <Plug>(ArticulateTag)
xmap  <C-.>  <Plug>(ArticulateTag)
nmap  <C-,>  <Plug>(ArticulatePop)
xmap  <C-,>  <Plug>(ArticulatePop)
nmap  g.     <Plug>(ArticulateTjump)
xmap  g.     <Plug>(ArticulateTjump)
```
But I didn't want my [`ftplugin/ruby.vim`](https://github.com/ivanbrennan/dotvim/blob/master/ftplugin/ruby.vim#L28-L31) to be coupled to the particulars of which keybindings I'd chosen. I wrote `articulate.vim` to provide generic `<Plug>` mappings that both `ruby.vim` and `keybindings.vim` could reference, without needing to know about each other.
```viml
" vim-ruby provides a command-line mapping for <Plug><cword> that
" intelligently identifies the current Ruby cursor identifier.
nmap <buffer><silent> <Plug>(ArticulateTag)   :<C-U>exe v:count1 "tag <Plug><cword>"<CR>
nmap <buffer><silent> <Plug>(ArticulateTjump) :<C-U>tjump <Plug><cword><CR>
```

It's a little complex for the purpose it serves, but I was getting a grip on Vim's `<Plug>` mappings, and I liked the solution conceptually.

If you were seeing `E426: tag not found: <Plug><cword>` before adding `articulate` to the mix, my best guess is you're not sourcing the runtime files that provide the Ruby-specific `<Plug><cword>` mapping, since the intention is to leverage that mapping to effectively replace `<Plug><cword>` on the command line with whichever Ruby identifier is under the cursor.

#### to debug:

I'd try running `:verbose cmap <Plug><cword>` from inside a Ruby buffer where the tags *are* working and see where it says the mapping is coming from. You could then revert to the broken setup and see why it's not picking up that source.

Out of curiosity, are you running Vim or Neovim, and are you using the vim-ruby plugin?

**Comment by zachahn** [comment]
Hey @ivanbrennan! Thanks for the detailed response!

I'm using Vim (version 8.0.636), and I'm not using the vim-ruby plugin (although I did try it, and I had the same error).

I just tried removing the the configuration (and articulate) altogether and like you said, it looks it all works! `<C-]>` differentiates between methods with and without the question mark suffix. Thanks for that info! haha. I guess problem solved, thanks! 😄 

I ran `:verbose cmap <Plug><cword>` while running vim without articulate or the nnoremaps, and I got this:

```
c  <Plug><cword> &@substitute(RubyCursorIdentifier(),'^$',"\022\027",'')
        Last set from /usr/local/Cellar/vim/8.0.0636/share/vim/vim80/ftplugin/ruby.vim
```

I'm just guessing, but it looks like everything should be working? But it all works now anyway lol. I may look into remapping to `<C-.` in the future if the current shortcut bothers me. Thanks again!

**Comment by ivanbrennan** [comment]
@zachahn Glad to hear it's all working. Yeah, that path,
```
/usr/local/Cellar/vim/8.0.0636/share/vim/vim80/ftplugin/ruby.vim
```
is one of the runtime files that comes included in Vim, and it was (mostly) contributed by tpope. It's where the ruby magic happens.
